name: ai_core_example
description: Example app demonstrating the ai_core package.

publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ai_core:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-ai.git

  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^9.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/sql/

dependency_overrides:
  ai_core:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-ai.git
  google_fonts: ^6.2.1
