name: ai_core_example
description: Example app demonstrating the ai_core package.

publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ai_core:
    git:
      url: http://xuan:***@192.168.0.165:3000/xuan/xuan-ai.git
      ref: main

  xuan_common:
    git:
      url: http://xuan:***@192.168.0.165:3000/xuan/xuan-common.git
      ref: main

  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/sql/

dependency_overrides:
  google_fonts: ^6.2.1
