targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      drift_dev:
        options:
          apply_converters_on_variables: true
          store_date_time_values_as_text: true
